#!/usr/bin/python

import setup
setup.pre_install()

from charmhelpers.core import hookenv
from charmhelpers.fetch import (
    configure_sources,
    apt_upgrade,
    apt_install,
)

PACKAGES = [ "contrail-web-controller", "nodejs=0.8.15-1contrail1",
             "supervisor", "contrail-utils" ]

def install():
    hookenv.log('Installing contrail-webui')

    configure_sources(True, "install-sources", "install-keys")
    apt_upgrade(fatal=True, dist=True)
    apt_install(PACKAGES, fatal=True)
    setup.fix_services()

if __name__ == "__main__":
    install()
