#!/bin/bash

source /home/stack/stackrc

flavor_list="
    contrail-controller
    contrail-analytics
    contrail-analytics-database"

for flavor in $flavor_list; do
    openstack flavor create $flavor --ram 4096 --vcpus 1 --disk 40
    openstack flavor set \
        --property "capabilities:boot_option"="local" \
        --property "capabilities:profile"="${flavor}" ${flavor}
done

