#!/bin/bash

hv[0]=10.84.29.5
hv[1]=10.84.29.6
hv[2]=10.84.29.7

list()
{
    for idx in 0 1 2; do
        addr=${hv[$idx]}
        echo "#### $addr"
        virsh -c qemu+ssh://root@$addr/system list --all
    done
}

create()
{
    for idx in 0 1 2; do
        addr=${hv[$idx]}
        echo "#### $addr"
        scp vm root@$addr:.
        ssh root@$addr ./vm delete $idx
        ssh root@$addr ./vm create $idx
        ssh root@$addr rm -f vm
    done
    list
}

delete()
{
    for idx in 0 1 2; do
        addr=${hv[$idx]}
        echo "#### $addr"
        scp vm root@$addr:.
        ssh root@$addr ./vm delete $idx
        ssh root@$addr rm -f vm
    done
    list
}

help()
{
    echo "$0 [create | delete]"
}

if [ $1 == "create" ]; then
    create
elif [ $1 == "delete" ]; then
    delete
else
    help
fi

exit 0

